name: Branch Check for Nightly
on:
  pull_request:
    branches:
      - nightly

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          if [[ "${{ github.head_ref }}" != "dev" ]]; then
            echo "Error: Pull request must come from 'dev' branch"
            echo "Source : ${{ github.head_ref }}"
            exit 1
          fi
          echo "Branch check passed. Target: ${{ github.base_ref }}, Source: ${{ github.head_ref }}"
