name: Branch Check for Dev
on:
  pull_request:
    branches:
      - dev

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          if [[ ! "${{ github.head_ref }}" =~ ^d[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Pull request must come from 'dX.X.X' branch (e.g., d0.4.2)"
            echo "Source : ${{ github.head_ref }}"
            exit 1
          fi
          echo "Branch check passed. Target: ${{ github.base_ref }}, Source: ${{ github.head_ref }}"
